# Generated by Django 5.2.5 on 2025-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_studentuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.RemoveField(
            model_name="student",
            name="std_class",
        ),
        migrations.AddField(
            model_name="student",
            name="cpassword",
            field=models.CharField(default="C", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="email@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="password", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="A", max_length=100),
        ),
    ]
