# Generated by Django 5.2.5 on 2025-08-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_remove_student_age_remove_student_roll_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="cpassword",
        ),
    ]
