# Generated by Django 5.2.5 on 2025-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_remove_student_cpassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="std_class",
            field=models.CharField(default="12th", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
