# Generated by Django 5.2.4 on 2025-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipes_name', models.CharField(max_length=100)),
                ('receipes_description', models.TextField()),
                ('receipes_image', models.ImageField(upload_to='recipe_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='recipe',
        ),
    ]
