# Generated by Django 5.2.4 on 2025-08-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_receipes_delete_recipe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="receipes",
            new_name="Recipe",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="receipes_description",
            new_name="recipe_description",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="receipes_image",
            new_name="recipe_image",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="receipes_name",
            new_name="recipe_name",
        ),
    ]
