# Generated by Django 5.2.4 on 2025-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0003_rename_receipes_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="vege\\static\\recipe_images"),
        ),
    ]
