# Generated by Django 5.2.5 on 2025-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0004_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="recipe_images/"),
        ),
    ]
