# Generated by Django 5.2.4 on 2025-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_student_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=200)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
    ]
